### ISSUE TITLE
Provide an API to integrate with clojure-lsp

### ISSUE THREAD

**Issue by fabiodomingues** [clj-depend/clj-depend#8]
In order to integrate with clojure-lsp (https://github.com/clojure-lsp/clojure-lsp/issues/957) we will provide an API that will be called from a custom linter inside clojure-lsp.

This API should be able to receive a sequence of namespaces and their dependencies, analyze, and then return violations, either just a specific namespace or all the namespaces in the project.

cc @ericdallo

**Comment by fabiodomingues** [comment]
I thought of two options for a public function that performs the analysis of dependencies between namespaces and return the violations.

---

**Option 1)** This option does not read the source files as it already receives the necessary dependencies for analyze each namespace.

This function would receive an options map containing the following required options:

- `:project-root` a java.io.File representing the project root (needed to get the configuration `.clj-depend/config.edn`).
- `:namespaces` a map of namespaces and their dependencies.

**Example**

 ```clojure
 (clj-depend.api/analyze {:project-root (io/file ".")
                          :namespaces [{:name "foo.a" :dependencies ["bar.y"]}
                                       {:name "bar.b" :dependencies ["bar.c"]}
                                       {:name "bar.c" :dependencies []}]})
 ```

---

**Option 2)** This option read the source files to parse namespace dependencies.

This function would receive an options map containing the following required options:

- `:project-root` a java.io.File representing the project root (needed to get the configuration `.clj-depend/config.edn`).
- `:namespaces` a set with only namespaces that need to be analyzed in the project.

**Example**

 ```clojure
 (clj-depend.api/analyze {:project-root (io/file ".")
                          :namespaces #{"foo.a" "foo.b"}})
 ```

---

As can be seen `clj-depend` treats namespaces as strings, I'm analyzing the impact also to change it to symbols as it seems to be better.

---

What do you think @ericdallo? Which of the above options is better for `clojure-lsp`?

**Comment by ericdallo** [comment]
@fabiodomingues great, looking forward for this API! 
Option 1 looks the fastest but even having clj-kondo analysis on clojure-lsp side, we would need to calculate all those dependencies which we don't do ATM, that's why option 2 seems to be better for clojure-lsp, how fast would option 1 be? I think not that relevant right?

Also, I'd suggest to the API be similar to kondo/cljfmt/clojure-lsp regarding accept clj-depend settings via a map, not only the file, this is useful since when using clojure-lsp people may have configs in a simple point and clojure-lsp have the logic to merge all settings, WDYT?
The same for project-root, maybe we could receive the source-paths via setting as well?

I'm imagining the API as something like:
```clojure
(clj-depend.api/analyze-dependencies {:settings {:layers {,,,}}
                                      :paths ["src" "test"]
                                      :namespaces '#{foo.a foo.b}}) ;; or as string, both would work I think
```

WDYT? do we need project-root to anything more? I think we could still support a project-root, but maybe supporting settings and paths would be better for clojure-lsp side

**Comment by fabiodomingues** [comment]
> Also, I'd suggest to the API be similar to kondo/cljfmt/clojure-lsp regarding accepting clj-depend settings via a map, not only the file, this is useful since when using clojure-lsp people may have configs in a simple point and clojure-lsp have the logic to merge all settings, WDYT?

Nice! If `clj-depend` receives a map in the settings we avoid having to search for them in the project-root.

> Also, we don't want to call clj-depend if no setting is available, right? that would be possible if we check there is no clj-depend settings available on lsp side

I agree, it makes sense!

> The same for project-root, maybe we could receive the source-paths via setting as well?
> WDYT? do we need project-root to anything more? I think we could still support a project-root, but maybe supporting settings and paths would be better for clojure-lsp side

Yes, getting the source-paths will help. I had forgotten about that because today lein provides both source-paths and project-root.
But we'll still need the project-root so we can go through the files to get the namespace dependencies we're going to analyze.

So maybe it would look like this:

```clojure
(clj-depend.api/analyze-dependencies {:settings {:layers {,,,}
                                                 :source-paths ["src"]}
                                      :project-root (io/file ".")
                                      :namespaces #{foo.a foo.b}})
```

WDYT @ericdallo? Makes sense?

**Comment by ericdallo** [comment]
Oh, I forgot clj-depend would still need to check the file content to check for dependencies on other ns... I see, I think there is no easy way to not need project root, not a problem though, but I think it'd be nice to support receiving the source paths as well as clojure-lsp already known them from a user configuration or auto discovery.

So your suggestion makes sense to me!

One question, I have no idea ATM how much time we would spend on clj-depend, just to have a base, how much time it takes to lint clojure-lsp project itself? It has 2 submodules: cli and lib, could you try that with a sample config just to make sure it's not that relevant?

**Comment by fabiodomingues** [comment]
The first version of the API was created!

You can use the namespace [clj-depend.api](https://cljdoc.org/d/com.fabiodomingues/clj-depend/CURRENT/api/clj-depend.api) to have access to all clj-depend features.

**Comment by ericdallo** [comment]
@fabiodomingues Awesome! Will give it a try

**Comment by fabiodomingues** [comment]
@ericdallo I took some time that clj-depend is taking to run with different options and here are the results:

- Analyzing all project:

  ```
  $ clj -M:clj-depend --project-root /home/fabio/development/src/clojure-lsp/lib
  Analyze took 138ms
  
  $ clj -M:clj-depend --project-root /home/fabio/development/src/clojure-lsp/lib
  Analyze took 122ms
  ```

- Analyzing a specific file:
  ```
  $ clj -M:clj-depend --project-root /home/fabio/development/src/clojure-lsp/lib --files /home/fabio/development/src/clojure-lsp/lib/src/clojure_lsp/internal_api.clj
  Analyze took 32ms
  
  $ clj -M:clj-depend --project-root /home/fabio/development/src/clojure-lsp/lib --files /home/fabio/development/src/clojure-lsp/lib/src/clojure_lsp/internal_api.clj
  Analyze took 23ms
  ```

- Analyzing a specific namespace:
  ```
  $ clj -M:clj-depend --project-root /home/fabio/development/src/clojure-lsp/lib --namespaces clojure-lsp.internal-api                                               
  Analyze took 134ms
  
  $ clj -M:clj-depend --project-root /home/fabio/development/src/clojure-lsp/lib --namespaces clojure-lsp.internal-api
  Analyze took 104ms
  ```

The result of parsing a specific namespace is taking approximately the same time as parsing the entire project. This happens because today to find the namespace it is necessary to scan all the files. It seems to have an opportunity for improvement, I'll leave it cataloged to work on it soon.

If you prefer, you can also use the `:files` option instead of `:namespaces`, and then clj-depend will scan only the specified files.

As we are getting the result in milliseconds, I think it's good to proceed with the first version.

WDYT?

**Comment by ericdallo** [comment]
Sure, that looks really promissing!
I'll get back to work on that PR this weekend on clojure-lsp to try to have something working so we can test on big real projects, if everything keeps stable and fast, we can probably merge to master :)
